SET SQL_SAFE_UPDATES = 0;
UPDATE menu_items SET image = '../images/salami-kashkawan.jpg' WHERE name = 'sulami pizza';
UPDATE menu_items SET image = '../images/pizza-meat.jpg' WHERE name = 'meat pizza';
UPDATE menu_items SET image = '../images/pizza-turkey.jpg' WHERE name = 'turkey pizza ';
UPDATE menu_items SET image = '../images/pizza-chicken-with-cream.jpg' WHERE name = 'chicken pizza';
UPDATE menu_items SET image = '../images/supreme-pizza.jpg' WHERE name = 'supreme pizza';
UPDATE menu_items SET image = '../images/pizza-zinger.jpg' WHERE name = 'zinger pizza';
UPDATE menu_items SET image = '../images/mana2eesh.jpg' WHERE name = 'mana2eesh';
UPDATE menu_items SET image = '../images/mana2eesh-with-cheese.jpg' WHERE name = 'manakeesh with cheese';
UPDATE menu_items SET image = '../images/turkey-and-kashkawan.jpg' WHERE name = 'turkey & kashkawan';
UPDATE menu_items SET image = '../images/salami-with-kashkawan.jpg' WHERE name = 'salami & cheese';
UPDATE menu_items SET image = '../images/mix-cheese.jpg' WHERE name = 'mix cheese';
UPDATE menu_items SET image = '../images/zinger-way.jpg' WHERE name = 'zinger way';
UPDATE menu_items SET image = '../images/corden-blue.jpg' WHERE name = 'corden blue';
UPDATE menu_items SET image = '../images/italian-chiken.jpg' WHERE name = 'corden blue';
UPDATE menu_items SET image = '../images/italian-chiken.jpg' WHERE name = 'italian chicken';
UPDATE menu_items SET image = '../images/meat-burger.jpg' WHERE name = 'meat burger';
UPDATE menu_items SET image = '../images/crispy-chicken-burger.jpg' WHERE name = 'chicken burger';
SET SQL_SAFE_UPDATES = 1;
