SET SQL_SAFE_UPDATES = 0;
UPDATE menu_items SET image = '../images/fahita.jpg' WHERE name = 'fahita';
UPDATE menu_items SET image = '../images/halloumi-sandwich.jpg' WHERE name = 'halloumi';
UPDATE menu_items SET image = '../images/kashkawan.jpg' WHERE name = 'kashkawan';
UPDATE menu_items SET image = '../images/yellow-cheese.jpeg' WHERE name = 'yellow cheese';
UPDATE menu_items SET image = '../images/labneh.webp' WHERE name = 'labneh';
UPDATE menu_items SET image = '../images/senioreh2.jpeg' WHERE name = 'labneh + senioreh';
UPDATE menu_items SET image = '../images/turkey.jpg' WHERE name = 'turkey';
UPDATE menu_items SET image = '../images/turkey-grill.jpeg' WHERE name = 'turkey grill';
UPDATE menu_items SET image = '../images/shawerma.jpg' WHERE name = 'shawarma small';
UPDATE menu_items SET image = '../images/shawerma.jpg' WHERE name = 'shawarma super';
UPDATE menu_items SET image = '../images/shawarma-meal.webp' WHERE name = 'shawarma meal';
UPDATE menu_items SET image = '../images/scaollop.jpg' WHERE name = 'scaollop';
UPDATE menu_items SET image = '../images/margrirta.jpeg' WHERE name = 'Margherita';
UPDATE menu_items SET image = '../images/vegetables-pizza.gif' WHERE name = 'Vegetables Pizza';
UPDATE menu_items SET image = '../images/potato.jpeg' WHERE name = 'potato';
UPDATE menu_items SET image = '../images/potato-sandwich.jpeg' WHERE name = 'potato Sandwich';
UPDATE menu_items SET image = '../images/potato-with-cheese.jpg' WHERE name = 'potato with cheese';
UPDATE menu_items SET image = '../images/zinger.jpeg' WHERE name = 'zinger';
UPDATE menu_items SET image = '../images/zinger-with-cheese.jpeg' WHERE name = 'zinger with cheese';
UPDATE menu_items SET image = '../images/barbican.png' WHERE name = 'barbican';
UPDATE menu_items SET image = '../images/barbican-cans.png' WHERE name = 'barbican cans';
UPDATE menu_items SET image = '../images/rani.png' WHERE name = 'rani';
UPDATE menu_items SET image = '../images/matrics.jpg' WHERE name = 'matrics';
UPDATE menu_items SET image = '../images/canary-chocolate.jpg' WHERE name = 'canary chocolate';
UPDATE menu_items SET image = '../images/chipseco.png' WHERE name = 'chipseco';
UPDATE menu_items SET image = '../images/sunbites.jpg' WHERE name = 'sunbite';
SET SQL_SAFE_UPDATES = 1;
