INSERT INTO menu_items (restaurant_id, name, price, image)
VALUES 
(1, 'fahita', 0.90, 'path/to/fahita.jpg'),
(1, 'halloumi', 0.50, 'path/to/halloumi-sandwich.jpg'),
(1, 'kashkawan', 0.50,'path/to/kashkawan.jpg'),
(1, 'yellow cheese', 0.50, 'path/to/yellow-cheese.jpeg'),
(1, 'labneh', 0.40, 'path/to/labneh.webp'),
(1, 'labneh + senioreh', 0.50, 'path/to/senioreh2.jpeg '),
(1, 'turkey', 0.80, 'path/to/turkey.jpg'),
(1, 'turkey grill', 1.00, 'path/to/turkey-grill.jpeg' ),
(1, 'shawarma small', 0.50, 'path/to/shawerma.jpg'),
(1, 'shawarma super', 1.00, 'path/to/shawerma.jpg'),
(1, 'shawarma meal', 2.00, 'path/to/shawarma-meal.webp'),
(1, 'scaollop', 0.60, 'path/to/scaollop.jpg'),
(1, 'Margherita', 0.45, 'path/to/margrirta.jpeg'),
(1, 'Vegetables Pizza', 0.60, 'path/to/vegetables-pizza.gif'),
(1, 'potato', 0.75, 'path/to/potato.jpeg'),
(1, 'potato Sandwich', 0.40, 'path/to/potato-sandwich.jpeg'),
(1, 'potato with cheese', 0.75, 'path/to/potato-with-cheese.jpg'),
(1, 'zinger', 1.40, 'path/to/zinger.jpeg'),
(1, 'zinger with cheese', 1.60, 'path/to/zinger-with-cheese.jpeg'),
(1, 'barbican', 0.65, 'path/to/barbican.png'),
(1, 'barbican cans', 0.50, 'path/to/barbican-cans.png'),
(1, 'rani', 0.50, 'path/to/rani.png'),
(1, 'matrics', 0.35, 'path/to/matrics.jpg'),
(1, 'canary chocolate', 0.25, 'path/to/canary-chocolate.jpg'),
(1, 'chipseco', 0.50, 'path/to/chipseco.png'),
(1, 'sunbite', 0.50, 'path/to/sunbites.jpg');