INSERT INTO menu_items (restaurant_id, name, price, image, menu_type)
VALUES 
(2, 'fahita', 0.90, '../images/snackway-menu/fahita.jpg', 'snackway-menu'),
(2, 'halloumi', 0.50, '../images/milkbar-menu/halloumi-sandwich.jpg','milkbar-menu'),
(2, 'kashkawan', 0.50, '../images/milkbar-menu/kashkawan.jpg','milkbar-menu'),
(2, 'yellow cheese', 0.50, '../images/milkbar-menu/yellow-cheese.jpeg','milkbar-menu'),
(2, 'labneh', 0.40, '../images/milkbar-menu/labneh.webp','milkbar-menu'),
(2, 'labneh + senioreh', 0.50, '../images/milkbar-menu/senioreh2.jpeg','milkbar-menu'),
(2, 'turkey', 0.80, '../images/milkbar-menu/turkey.jpg','milkbar-menu'),
(2, 'turkey grill', 1.00, '../images/milkbar-menu/turkey-grill.jpeg','milkbar-menu' ),
(2, 'shawarma small', 0.50, '../images/milkbar-menu/shawerma.jpg','milkbar-menu'),
(2, 'shawarma super', 1.00, '../images/milkbar-menu/shawerma.jpg','milkbar-menu'),
(2, 'shawarma meal', 2.00, '../images/milkbar-menu/shawarma-meal.webp','milkbar-menu'),
(2, 'scaollop', 0.60, '../images/milkbar-menu/scaollop.jpg','milkbar-menu'),
(2, 'Margherita', 0.45, '../images/saj-menu/margrirta.jpeg','saj-menu'),
(2, 'Vegetables Pizza', 0.60, '../images/snackway-menu/vegetables-pizza.gif', 'snackway-menu'),
(2, 'potato', 0.75, '../images/milkbar-menu/potato.jpeg','milkbar-menu'),
(2, 'potato Sandwich', 0.40, '../images/saj-menu/potato-sandwich.jpeg','saj-menu'),
(2, 'potato with cheese', 0.75, '../images/milkbar-menu/potato-with-cheese.jpg','milkbar-menu'),
(2, 'zinger', 1.40, '../images/milkbar-menu/zinger.jpeg','milkbar-menu'),
(2, 'zinger with cheese', 1.60, '../images/milkbar-menu/zinger-with-cheese.jpeg','milkbar-menu'),
(2, 'barbican', 0.65, '../images/milkbar-menu/barbican.png','milkbar-menu'),
(2, 'barbican cans', 0.50, '../images/milkbar-menu/barbican-cans.png','milkbar-menu'),
(2, 'rani', 0.50, '../images/milkbar-menu/rani.png','milkbar-menu'),
(2, 'matrics', 0.35, '../images/milkbar-menu/matrics.jpg','milkbar-menu'),
(2, 'canary chocolate', 0.25, '../images/milkbar-menu/canary-chocolate.jpg','milkbar-menu'),
(2, 'chipseco', 0.50, '../images/milkbar-menu/chipseco.png','milkbar-menu'),
(2, 'sunbite', 0.50, '../images/milkbar-menu/sunbites.jpg','milkbar-menu');