INSERT INTO menu_items (restaurant_id, name, price, image, menu_type) VALUES
(4, 'chicken with cream', 2.50, '../images/snackway-menu/pizza-chicken-with-cream.jpg', 'pizza'),
(4, '4 season pizza', 2.50, '../images/snackway-menu/pizza-4-seasons.jpg', 'pizza'),
(4, 'zinger pizza', 2.50, '../images/snackway-menu/pizza-zinger.jpg', 'pizza'),
(4, 'meat pizza', 2.50, '../images/snackway-menu/pizza-meat.jpg', 'pizza'),
(4, 'vegetables pizza', 2.00, '../images/snackway-menu/pizza-vegetables.jpg', 'pizza'),
(4, 'hotdog pizza', 2.00, '../images/snackway-menu/pizza-hotdog.jpg', 'pizza'),
(4, 'supreme pizza', 2.25, '../images/snackway-menu/supreme-pizza.jpg', 'pizza'),
(4, 'salami pizza', 2.25, '../images/snackway-menu/pizza-salami.jpg', 'pizza'),
(4, 'mix cheese & turkey', 2.00, '../images/snackway-menu/mix-cheese-with-turkey.jpg', 'manakeesh'),
(4, 'turkey & kashkawan', 1.75, '../images/snackway-menu/turkey-and-kashkawan.jpg', 'manakeesh'),
(4, 'halloum', 1.00, '../images/snackway-menu/halloum.jpg', 'manakeesh'),
(4, 'mix cheese', 2.00, '../images/snackway-menu/mix-cheese-sandwich.jpg', 'manakeesh'),
(4, 'manakeesh', 0.75, '../images/snackway-menu/mana2eesh.jpg', 'manakeesh'),
(4, 'manakeesh with cheese', 1.25, '../images/snackway-menu/mana2eesh-with-cheese.jpg', 'manakeesh'),
(4, 'salami & kashkawan', 1.50, '../images/snackway-menu/salami-with-kashkawan.jpg', 'manakeesh'),
(4, 'hotdog & kashkawan', 1.75, '../images/snackway-menu/hotdog-with-kashkawan.jpg', 'manakeesh'),
(4, 'mix-cheese', 2.00, '../images/snackway-menu/mix-cheese.jpg', 'manakeesh'),
(4, 'zinger way', 2.00, '../images/snackway-menu/zinger-way.jpg', 'snacks'),
(4, 'corden blue', 2.00, '../images/snackway-menu/corden-blue.jpg', 'snacks'),
(4, 'fahita', 2.00, '../images/snackway-menu/fahita.jpg', 'snacks'),
(4, 'steak', 2.00, '../images/snackway-menu/steak.jpg', 'snacks'),
(4, 'chicken with cream', 2.00, '../images/snackway-menu/cream-chicken.jpg', 'snacks'),
(4, 'sheesh tawooq', 2.00, '../images/snackway-menu/sheesh-tawooq.jpg', 'snacks'),
(4, 'italian chicken', 2.00, '../images/snackway-menu/italian-chiken.jpg', 'snacks'),
(4, 'scallop', 2.00, '../images/snackway-menu/escallop.jpg', 'snacks'),
(4, 'kasadia', 2.00, '../images/snackway-menu/kasadia.jpg', 'snacks'),
(4, 'meat burger', 2.00, '../images/snackway-menu/meat-burger.jpg', 'burger'),
(4, 'burger barbecue', 2.00, '../images/snackway-menu/burger-barbecue.jpg', 'burger'),
(4, 'classic burger', 2.00, '../images/snackway-menu/classic-burger.jpg', 'burger'),
(4, 'burger cream & mushroom', 2.00, '../images/snackway-menu/burger-with-cream-and-mushroom.jpg', 'burger'),
(4, 'chicken with cream', 2.00, '../images/snackway-menu/crispy-chicken-burger.jpg', 'burger'),
(4, 'shawarma meat', 1.75, '../images/snackway-menu/shawarma-meat.jpg', 'shawarma'),
(4, 'shawarma meat meal', 2.75, '../images/snackway-menu/shawarma-meat-meal.jpg', 'shawarma'),
(4, 'shawarma', 1.50, '../images/snackway-menu/shawerma.jpg', 'shawarma'),
(4, 'shwarma ordinary meal', 2.50, '../images/snackway-menu/shawarm-chicke-ord-meal.jpg', 'shawarma');
